# Generated by Django 4.0 on 2022-01-18 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='15 Ikoyi', max_length=300)),
                ('email', models.CharField(default='eniola@gmail.com', max_length=200)),
                ('age', models.IntegerField(default=3)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lead.user')),
            ],
        ),
    ]
